import { RegistrationData } from '@/types/registration';

// Mock registration data for demo purposes
export const mockRegistrations: RegistrationData[] = [
  {
    registrationId: 'JAN2026-1001',
    phone: '9876543210',
    role: 'student',
    studentName: 'Rajesh Kumar',
    dateOfBirth: '2008-05-15',
    gender: 'Male',
    email: 'rajesh.kumar@example.com',
    grade: 'Grade 10',
    schoolName: 'National Public School',
    schoolCity: 'Bangalore',
    schoolState: 'Karnataka',
    parentName: 'Suresh Kumar',
    parentEmail: 'suresh.kumar@example.com',
    parentPhone: '9876543211',
    relationship: 'Father',
    category: 'essay_writing',
    language: 'en',
    referralSource: 'Social Media',
  },
  {
    registrationId: 'JAN2026-1002',
    phone: '9876543212',
    role: 'parent',
    studentName: 'ಪ್ರಿಯಾ ರಾಮಚಂದ್ರನ್',
    dateOfBirth: '2009-08-22',
    gender: 'Female',
    email: 'priya.r@example.com',
    grade: 'Grade 9',
    schoolName: 'ಸರಸ್ವತಿ ವಿದ್ಯಾಲಯ',
    schoolCity: 'Bangalore',
    schoolState: 'Karnataka',
    parentName: 'ರಾಮಚಂದ್ರನ್ ಐಯರ್',
    parentEmail: 'ramachandran@example.com',
    parentPhone: '9876543213',
    relationship: 'Mother',
    category: 'short_story',
    language: 'kn',
    referralSource: 'School',
  },
  {
    registrationId: 'JAN2026-1003',
    phone: '9876543214',
    role: 'student',
    studentName: 'Arjun Reddy',
    dateOfBirth: '2007-11-30',
    gender: 'Male',
    email: 'arjun.reddy@example.com',
    grade: 'Grade 11',
    schoolName: 'Delhi Public School',
    schoolCity: 'Bangalore',
    schoolState: 'Karnataka',
    parentName: 'Venkatesh Reddy',
    parentEmail: 'venkatesh.r@example.com',
    parentPhone: '9876543215',
    relationship: 'Father',
    category: 'poetry',
    language: 'en',
    referralSource: 'Friend',
  },
  {
    registrationId: 'JAN2026-1004',
    phone: '9876543216',
    role: 'parent',
    studentName: 'ಅನನ್ಯಾ ಶೆಟ್ಟಿ',
    dateOfBirth: '2008-03-18',
    gender: 'Female',
    email: 'ananya.s@example.com',
    grade: 'Grade 10',
    schoolName: 'ವಿದ್ಯಾ ವಿಹಾರ ಶಾಲೆ',
    schoolCity: 'Bangalore',
    schoolState: 'Karnataka',
    parentName: 'ಸುಧಾ ಶೆಟ್ಟಿ',
    parentEmail: 'sudha.shetty@example.com',
    parentPhone: '9876543217',
    relationship: 'Mother',
    category: 'essay_writing',
    language: 'kn',
    referralSource: 'Newspaper',
  },
  {
    registrationId: 'JAN2026-1005',
    phone: '9876543218',
    role: 'student',
    studentName: 'Kavya Sharma',
    dateOfBirth: '2009-07-25',
    gender: 'Female',
    email: 'kavya.sharma@example.com',
    grade: 'Grade 9',
    schoolName: 'Bishop Cotton School',
    schoolCity: 'Bangalore',
    schoolState: 'Karnataka',
    parentName: 'Ramesh Sharma',
    parentEmail: 'ramesh.sharma@example.com',
    parentPhone: '9876543219',
    relationship: 'Father',
    category: 'creative_nonfiction',
    language: 'en',
    referralSource: 'Website',
  },
  {
    registrationId: 'JAN2026-1006',
    phone: '9876543220',
    role: 'student',
    studentName: 'ವಿಕ್ರಮ್ ಗೌಡ',
    dateOfBirth: '2008-12-10',
    gender: 'Male',
    email: 'vikram.g@example.com',
    grade: 'Grade 10',
    schoolName: 'ಶ್ರೀ ರಾಮ ಶಾಲೆ',
    schoolCity: 'Bangalore',
    schoolState: 'Karnataka',
    parentName: 'ರಾಜು ಗೌಡ',
    parentEmail: 'raju.gowda@example.com',
    parentPhone: '9876543221',
    relationship: 'Father',
    category: 'short_story',
    language: 'kn',
  },
  {
    registrationId: 'JAN2026-1007',
    phone: '9876543222',
    role: 'parent',
    studentName: 'Meera Patel',
    dateOfBirth: '2007-09-05',
    gender: 'Female',
    email: 'meera.patel@example.com',
    grade: 'Grade 11',
    schoolName: 'Christ School',
    schoolCity: 'Bangalore',
    schoolState: 'Karnataka',
    parentName: 'Nilesh Patel',
    parentEmail: 'nilesh.patel@example.com',
    parentPhone: '9876543223',
    relationship: 'Father',
    category: 'essay_writing',
    language: 'en',
    referralSource: 'Email',
  },
  {
    registrationId: 'JAN2026-1008',
    phone: '9876543224',
    role: 'student',
    studentName: 'ದೀಪಕ್ ನಾಯಕ್',
    dateOfBirth: '2009-01-14',
    gender: 'Male',
    email: 'deepak.n@example.com',
    grade: 'Grade 9',
    schoolName: 'ಕರ್ನಾಟಕ ಶಾಲೆ',
    schoolCity: 'Bangalore',
    schoolState: 'Karnataka',
    parentName: 'ಶಂಕರ ನಾಯಕ್',
    parentEmail: 'shankar.nayak@example.com',
    parentPhone: '9876543225',
    relationship: 'Father',
    category: 'poetry',
    language: 'kn',
    referralSource: 'Social Media',
  },
  {
    registrationId: 'JAN2026-1009',
    phone: '9876543226',
    role: 'student',
    studentName: 'Aisha Khan',
    dateOfBirth: '2008-06-20',
    gender: 'Female',
    email: 'aisha.khan@example.com',
    grade: 'Grade 10',
    schoolName: 'Baldwin School',
    schoolCity: 'Bangalore',
    schoolState: 'Karnataka',
    parentName: 'Farid Khan',
    parentEmail: 'farid.khan@example.com',
    parentPhone: '9876543227',
    relationship: 'Father',
    category: 'creative_nonfiction',
    language: 'en',
    referralSource: 'Friend',
  },
  {
    registrationId: 'JAN2026-1010',
    phone: '9876543228',
    role: 'parent',
    studentName: 'ಸಾಕ್ಷಿ ಕುಮಾರಿ',
    dateOfBirth: '2009-04-12',
    gender: 'Female',
    email: 'sakshi.k@example.com',
    grade: 'Grade 9',
    schoolName: 'ಸಾಹಿತ್ಯ ವಿದ್ಯಾಲಯ',
    schoolCity: 'Bangalore',
    schoolState: 'Karnataka',
    parentName: 'ಲಕ್ಷ್ಮಿ ಕುಮಾರಿ',
    parentEmail: 'lakshmi.k@example.com',
    parentPhone: '9876543229',
    relationship: 'Mother',
    category: 'short_story',
    language: 'kn',
    referralSource: 'School',
  },
];

// Helper function to get registration statistics
export function getRegistrationStats() {
  const total = mockRegistrations.length;
  const byLanguage = {
    english: mockRegistrations.filter(r => r.language === 'en').length,
    kannada: mockRegistrations.filter(r => r.language === 'kn').length,
  };
  const byCategory = {
    essay_writing: mockRegistrations.filter(r => r.category === 'essay_writing').length,
    short_story: mockRegistrations.filter(r => r.category === 'short_story').length,
    poetry: mockRegistrations.filter(r => r.category === 'poetry').length,
    creative_nonfiction: mockRegistrations.filter(r => r.category === 'creative_nonfiction').length,
  };
  const byGrade = {
    grade9: mockRegistrations.filter(r => r.grade === 'Grade 9').length,
    grade10: mockRegistrations.filter(r => r.grade === 'Grade 10').length,
    grade11: mockRegistrations.filter(r => r.grade === 'Grade 11').length,
    grade12: mockRegistrations.filter(r => r.grade === 'Grade 12').length,
  };

  return {
    total,
    byLanguage,
    byCategory,
    byGrade,
  };
}

// Helper function to search registrations
export function searchRegistrations(query: string): RegistrationData[] {
  const lowerQuery = query.toLowerCase();
  return mockRegistrations.filter(
    r =>
      r.registrationId?.toLowerCase().includes(lowerQuery) ||
      r.studentName.toLowerCase().includes(lowerQuery) ||
      r.email.toLowerCase().includes(lowerQuery) ||
      r.phone.includes(query) ||
      r.schoolName.toLowerCase().includes(lowerQuery)
  );
}
